name: Salsah Model Visualisation

on:
  workflow_dispatch: # trigger manually

# globals
env:
  SCRIPT_DIR: 1_salsah-model-extraction
  ARCHIVE_DIR: archive


jobs:
  visualise_salsah_model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - run: java -version
      
      - name: Create visualization template
        working-directory: ${{ github.workspace }}/${{ env.SCRIPT_DIR }}
        run: python VisualizeJson.py
        
      - name: Validate
        working-directory: ${{ github.workspace }}/${{ env.SCRIPT_DIR }}
        run: ls -R
      
      - name: Install & run PlantUML
        working-directory: ${{ github.workspace }}/${{ env.SCRIPT_DIR }}
        run: | 
          wget -O plantuml.jar https://sourceforge.net/projects/plantuml/files/plantuml.jar
          java -jar plantuml.jar -v -tsvg webern_*_plantuml.txt
      
